[tool.black]
line-length = 99
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
| nbautoexport/_version.py
'''

[build-system]
requires = [
    "setuptools<=63",
    "versioneer",
    "wheel",
]
build-backend = "setuptools.build_meta"