strategy:
  matrix:
    LinuxPython36:
      pythonVersion: '3.6'
      imageName: 'ubuntu-16.04'
    MacPython36:
       pythonVersion: '3.6'
       imageName: 'macOS-10.14'
    WinPython36:
      pythonVersion: '3.6'
      imageName: 'vs2017-win2016'

pool:
  vmImage: '$(imageName)'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
  - bash: |
      pip install .
      pip install -r requirements-dev.txt
    displayName: Install package and dev requirements
  - bash: make lint
    displayName: Code quality checks
  - bash: make test
