jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
      - bash: |
          pip install .
          pip install -r requirements-dev.txt
        displayName: Install package and dev requirements
      - bash: make lint
        displayName: Code quality checks
          
